name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  cdk-synth:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install -g yarn
        yarn

    # - name: Test
    #   run: |
    #     yarn test

    - name: CDK Synth
      run: |
        yarn synth:dev
